import enum

Letters = enum.Enum(
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
    'BLANK'
)

COUNT = {
    Letters.A: 9,
    Letters.B: 2,
    Letters.C: 2,
    Letters.D: 4,
    Letters.E: 12,
    Letters.F: 2,
    Letters.G: 3,
    Letters.H: 2,
    Letters.I: 9,
    Letters.J: 1,
    Letters.K: 1,
    Letters.L: 4,
    Letters.M: 2,
    Letters.N: 6,
    Letters.O: 8,
    Letters.P: 2,
    Letters.Q: 1,
    Letters.R: 6,
    Letters.S: 4,
    Letters.T: 6,
    Letters.U: 4,
    Letters.V: 2,
    Letters.W: 2,
    Letters.X: 1,
    Letters.Y: 2,
    Letters.Z: 1,
    Letters.BLANK: 2
}

POINTS = {
    Letters.A: 1,
    Letters.B: 3,
    Letters.C: 3,
    Letters.D: 2,
    Letters.E: 1,
    Letters.F: 4.
    Letters.G: 2,
    Letters.H: 4,
    Letters.I: 1,
    Letters.J: 8,
    Letters.K: 5,
    Letters.L: 1,
    Letters.M: 3,
    Letters.N: 1.
    Letters.O: 1,
    Letters.P: 3,
    Letters.Q: 10,
    Letters.R: 1,
    Letters.S: 1,
    Letters.T: 1,
    Letters.U: 1,
    Letters.V: 8,
    Letters.W: 4,
    Letters.X: 8,
    Letters.Y: 4,
    Letters.Z: 10,
    Letters.BLANK: 0
}